refume/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  #resources :matches
  root   'static_pages#home'
  get    '/home',          to: 'static_pages#home'
  get    '/help',          to: 'static_pages#help'
  get    '/about',         to: 'static_pages#about'
  get    '/info',          to: 'static_pages#info'
  get    '/contact',       to: 'static_pages#contact'
  get    '/signup',        to: 'users#new'
  get    '/select',        to: 'users#select'
  post   '/select',        to: 'users#role_select'
  get    '/mentor_mentee', to: 'users#mentor_mentee'
  get    '/login',         to: 'sessions#new'
  post   '/login',         to: 'sessions#create'
  delete '/logout',        to: 'sessions#destroy'
  get    '/microposts',     to: 'microposts#index'
  post   '/microposts',     to: 'microposts#create'
  post   '/matches/new',   to: 'matches#create'
  get    '/matches/:id',   to: 'matches#show'
  resources :users
  resources :matches
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

refume/app/models/match.rb
class Match < ApplicationRecord
  # since matches involve two users
  # a match belongs to both a mantor and a mentee
  #belongs_to :mentor, class_name: "User"
  #belongs_to :mentee, class_name: "User"
  #validates  :mentor_id, presence: true
  #validates  :mentee_id, presence: true
end

refume/app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    #should be the following line when our matching feature is implemented
    @user = current_user
    #@matches = Match.All
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @user = current_user
    #@match = params[:id]
    #get all the matched mentors/mentees for this user
    @matches = nil
    if @user.role == "Mentee"
      @matches = Match.where(mentee_id: @user.id)
    elsif @user.role == "Mentor"
      @matches = Match.where(mentor_id: @user.id)
    end
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @user = current_user
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:mentor_id, :mentee_id, :created_at, :updated_at)
    end
end

refume/app/helpers/matches_helper.rb
module MatchesHelper
end

refume/app/views/matches/_form.html.erb
<%= form_with(model: match, local: true) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mentor_id %>
    <%= form.number_field :mentor_id, id: :match_mentor_id %>
  </div>

  <div class="field">
    <%= form.label :mentee_id %>
    <%= form.number_field :mentee_id, id: :match_mentee_id %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.datetime_select :created_at, id: :match_created_at %>
  </div>

  <div class="field">
    <%= form.label :updated_at %>
    <%= form.datetime_select :updated_at, id: :match_updated_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

refume/app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

refume/app/views/matches/index.html.erb
<% provide(:title, "Match result") %>
<br>
<div class="row" style="text-align:center;">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to 'Get Match', "/matches/#{@user.id}", {:style => 'font-size:20px;'} %>
  </div>
</div>

<!-- < %= link_to 'New Match', new_match_path "/matches/#{@user.id}" %> -->

refume/app/views/matches/new.html.erb
<% provide(:title, "New Match") %>
<h1>New Match</h1>

<!-- < %= render 'form', match: @match %> -->

<%= link_to 'Back', matches_path %>

refume/app/views/matches/show.html.erb
<% provide(:title, "Show Match") %>
<p id="notice"><%= notice %></p>

<h2>Show Matches </h2>
<%= "This is " + @user.name + ", who is a "%>
<% if @user.role %>
  <%= @user.role + "." %>
<% else %>
  <%= "neither role." %>
<% end %>

<br>
<!-- < %= link_to 'Edit', edit_match_path(@match) %> | -->
<%= link_to 'Back', matches_path %>