refume/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  #resources :matches
  root   'static_pages#home'
  get    '/home',          to: 'static_pages#home'
  get    '/help',          to: 'static_pages#help'
  get    '/about',         to: 'static_pages#about'
  get    '/info',          to: 'static_pages#info'
  get    '/contact',       to: 'static_pages#contact'
  get    '/signup',        to: 'users#new'
  get    '/select',        to: 'users#select'
  post   '/select',        to: 'users#role_select'
  get    '/mentor_mentee', to: 'users#mentor_mentee'
  get    '/login',         to: 'sessions#new'
  post   '/login',         to: 'sessions#create'
  delete '/logout',        to: 'sessions#destroy'
  get    '/microposts',     to: 'microposts#index'
  post   '/microposts',     to: 'microposts#create'
  post   '/matches/new',   to: 'matches#create'
  get    '/matches/:id',   to: 'matches#show'
  resources :users
  resources :matches
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

refume/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-expand-sm navbar-inverse">
  <div class="container">
    <span style="width:70px;">
      <%= image_tag("RefuMe-Logo.png", size: "60x60", class: "rounded float-left") %>
    </span>
    <nav>
      <%= link_to "RefuMe", root_path, id: "logo" %>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path, {:style => 'font-size:20px;'} %></li>
        <% if logged_in? %>
          <li><%= link_to "Info", info_path, {:style => 'font-size:20px;'} %></li>
          <li><%= link_to "Discussion Forum", "/posts", {:style => 'font-size:20px;'}%></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="font-size:20px">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user, {:style => 'font-size:15px;'} %></li>
              <li><%= link_to "Settings", edit_user_path(current_user), {:style => 'font-size:15px;'} %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path, {:style => 'font-size:20px;'}%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<br>

refume/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | RefuMe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>